title: Kara Kraus
# logo:
description: Automation
show_downloads: false
# theme: jekyll-theme-minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/kwhaley
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/kwhaley


navigation:
  - name: About Me
    link: /Kara_Portfolio/index.html#about-me
  - name: Projects Overview
    link: /Kara_Portfolio/index.html#projects-overview
    sublist:
      - name: Data Automation
        link: /Kara_Portfolio/index.html#data-automation
      - name: Volunteer System
        link: /Kara_Portfolio/index.html#auto-volunteer
      - name: CMS Migration
        link: /Kara_Portfolio/index.html#cms-migration
      - name: Tracking System
        link: /Kara_Portfolio/index.html#tracking-system
      - name: Payroll System
        link: /Kara_Portfolio/index.html#payroll-system
      - name: E-comm Website
        link: /Kara_Portfolio/index.html#ecomm-website
  - name: Case Studies
    # link: #
    sublist:
      - name: Volunteer Reservation System
        link: /Kara_Portfolio/case-studies/volunteer-reservation-brownhoist.html
      - name: Data Automation
        link: /Kara_Portfolio/case-studies/data-automation-reading-room.html
  - name: Skills & Tools
      link: /Kara_Portfolio/index.html#skills
  - name: Testimonials
    link: /Kara_Portfolio/index.html#testimonials
